services:
  ipv4-server:
    container_name: ipv4-server
    build:
      context: ./ipv4-server
      dockerfile: Dockerfile
    networks:
      - ipv4-net
    command: ["/server"]

  ipv6-client:
    container_name: ipv6-client
    build:
      context: ./ipv6-client
      dockerfile: Dockerfile
    networks:
      - ipv6-net
    entrypoint: ["/entrypoint.sh"]

networks:
  ipv4-net:
    external: true
    name: ipv4_net

  ipv6-net:
    external: true
    name: ipv6_net
