version: "3.8"

services:
  ipv6-client:
    build: ./ipv6-client
    container_name: ipv6-client
    volumes:
      - ./bridge-sync:/bridge   # Shared volume
    networks:
      ipv6_net:
        ipv6_address: "fd42:4242:4242::10"
    tty: true



  ipv4-server:
    build: ./ipv4-server
    container_name: ipv4-server
    networks:
      ipv4_net:
        ipv4_address: "192.0.2.10"
    tty: true

networks:
  ipv6_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fd42:4242:4242::/64"

  ipv4_net:
    driver: bridge
    ipam:
      config:
        - subnet: "192.0.2.0/24"

